# Generated by Django 4.2.6 on 2023-10-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('board_title', models.CharField(blank=True, max_length=100, null=True)),
                ('board_main_txt', models.TextField(blank=True, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('lst_chg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment_text', models.CharField(blank=True, max_length=200, null=True)),
                ('reg_date', models.DateTimeField(blank=True, null=True)),
                ('lst_chg_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'board_comment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageCode',
            fields=[
                ('language_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('language_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'language_code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('user_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_password', models.CharField(blank=True, max_length=30, null=True)),
                ('user_name', models.CharField(blank=True, max_length=150, null=True)),
                ('user_email', models.CharField(blank=True, max_length=254, null=True)),
                ('user_website_url', models.CharField(blank=True, max_length=50, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('frst_login_date', models.DateField(blank=True, null=True)),
                ('is_superuser', models.IntegerField(blank=True, null=True)),
                ('is_staff', models.IntegerField(blank=True, null=True)),
                ('is_active', models.IntegerField(blank=True, null=True)),
                ('user_language', models.CharField(blank=True, max_length=10, null=True)),
                ('user_level', models.CharField(blank=True, max_length=10, null=True)),
                ('avatar', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user_info',
                'managed': False,
            },
        ),
    ]
