# Generated by Django 4.2.6 on 2023-10-18 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language_Code',
            fields=[
                ('language_id', models.CharField(db_column='language_id', max_length=10, primary_key=True, serialize=False)),
                ('language_name', models.CharField(db_column='language_name', max_length=30)),
            ],
            options={
                'db_table': 'language_code',
                'managed': False,
            },
        ),
    ]
