# Generated by Django 4.2.6 on 2023-10-19 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=10, verbose_name='Level'),
        ),
    ]
