<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-10-24 02:22
=======
# Generated by Django 4.2.1 on 2023-10-23 05:00
>>>>>>> ldh

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("roleplay_game_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayingroom',
            name='helper_role',
            field=models.CharField(max_length=100, verbose_name='도우미 역할'),
            model_name="roleplayingroom",
            name="helper_role",
            field=models.CharField(max_length=100, verbose_name="도우미 역할"),
        ),
    ]
