# Generated by Django 4.2.1 on 2023-10-24 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roleplay_game_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roleplayingroom',
            name='helper_role',
            field=models.CharField(max_length=100, verbose_name='도우미 역할'),
        ),
    ]
